services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SBUERK\LegacyParamGuard\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  SBUERK\LegacyParamGuard\SimpleService:
    public: true
